# .rubocop.yml

# inherit_gem:
#   rubocop-rails-omakase: rubocop.yml
require:
  - rubocop-rails

AllCops:
  # NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/queue_schema.rb"
    - "db/cache_schema.rb"
    - "db/cache_schema.rb"
    - "bin/*"
    - "config/puma.rb"
    - "spec/*"

Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Width: 2

Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/TrailingWhitespace:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  Max: 25

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false
